### ISSUE TITLE
no longer works, ass.

### ISSUE THREAD

**Issue by ImInTheICU** [tickwares/tickware#1]

**Comment by tickwares** [comment]
First off, Synapse is down.
Second, I use Synapse to decompile their anticheat and find what they have added.
And also I won't use getgc.

**Comment by ImInTheICU** [comment]
Interesting Synapse has been down for 3 months?
Also why not use getgc()?

**Comment by tickwares** [comment]
It causes some lag whenever you loop it

**Comment by ImInTheICU** [comment]
This aged well.
